---
  - hosts: localhost
    connection: local
#    become: yes
#    vars:
#      ansible_become_pass: "password123"
    tasks:
      - name: Create directory
        file:
          path: /root/test-directory
          state: directory
          mode: 0755
          owner: root
          group: root
          recurse: yes

      - name: Print
        debug:
          msg: "Hello World"